apiVersion: apps/v1
kind: Deployment
metadata:
  name: logcloak
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logcloak
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: logcloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logcloak
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: webhook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: https
          containerPort: 8443
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65534
      - name: controller
        image: "{{ .Values.controller.image }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65534
