apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logcloak-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logcloak
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logcloak-operator
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
