apiVersion: v1
kind: Service
metadata:
  name: logcloak-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logcloak
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: logcloak
  ports:
  - name: https
    port: 443
    targetPort: 8443
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: {{ .Values.metrics.port }}
