apiVersion: v1
kind: Secret
metadata:
  name: logcloak-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logcloak
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
  ca.crt: ""
